services:
  stremio-rss-catalog-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stremio-rss-catalog-dev
    restart: unless-stopped
    ports:
      - "17973:7000"
    volumes:
      - ./work-data:/data
    environment:
      PORT: "7000"
      NODE_ENV: development
      TZ: Europe/Paris
      WEBUI_USERNAME: admin
      WEBUI_PASSWORD: admin
      DB_PATH: /data/addon.db
      SESSION_SECRET: local-development-only-change-me
